/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModIndexRouteImport } from './routes/mod.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SubSubIdRouteImport } from './routes/sub.$subId'
import { Route as ModAuditRouteImport } from './routes/mod.audit'
import { Route as AppAppIdRouteImport } from './routes/app.$appId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminCookiesRouteImport } from './routes/admin.cookies'
import { Route as GSlugIndexRouteImport } from './routes/g.$slug.index'
import { Route as USteamSteamIdRouteImport } from './routes/u.steam.$steamId'
import { Route as ModWinsWinIdRouteImport } from './routes/mod.wins.$winId'
import { Route as ModGSlugRouteImport } from './routes/mod.g.$slug'
import { Route as GSlugWinsRouteImport } from './routes/g.$slug.wins'
import { Route as AuthSteamStartRouteImport } from './routes/auth.steam.start'
import { Route as AuthSteamCallbackRouteImport } from './routes/auth.steam.callback'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as GSlugGiveawaysIndexRouteImport } from './routes/g.$slug.giveaways.index'
import { Route as GSlugGiveawaysCodeRouteImport } from './routes/g.$slug.giveaways.$code'
import { Route as GSlugGiveawaysByIdGiveawayIdRouteImport } from './routes/g.$slug.giveaways.by-id.$giveawayId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModIndexRoute = ModIndexRouteImport.update({
  id: '/mod/',
  path: '/mod/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SubSubIdRoute = SubSubIdRouteImport.update({
  id: '/sub/$subId',
  path: '/sub/$subId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModAuditRoute = ModAuditRouteImport.update({
  id: '/mod/audit',
  path: '/mod/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdRoute = AppAppIdRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCookiesRoute = AdminCookiesRouteImport.update({
  id: '/admin/cookies',
  path: '/admin/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugIndexRoute = GSlugIndexRouteImport.update({
  id: '/g/$slug/',
  path: '/g/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const USteamSteamIdRoute = USteamSteamIdRouteImport.update({
  id: '/u/steam/$steamId',
  path: '/u/steam/$steamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModWinsWinIdRoute = ModWinsWinIdRouteImport.update({
  id: '/mod/wins/$winId',
  path: '/mod/wins/$winId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModGSlugRoute = ModGSlugRouteImport.update({
  id: '/mod/g/$slug',
  path: '/mod/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugWinsRoute = GSlugWinsRouteImport.update({
  id: '/g/$slug/wins',
  path: '/g/$slug/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamStartRoute = AuthSteamStartRouteImport.update({
  id: '/auth/steam/start',
  path: '/auth/steam/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamCallbackRoute = AuthSteamCallbackRouteImport.update({
  id: '/auth/steam/callback',
  path: '/auth/steam/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const GSlugGiveawaysIndexRoute = GSlugGiveawaysIndexRouteImport.update({
  id: '/g/$slug/giveaways/',
  path: '/g/$slug/giveaways/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugGiveawaysCodeRoute = GSlugGiveawaysCodeRouteImport.update({
  id: '/g/$slug/giveaways/$code',
  path: '/g/$slug/giveaways/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugGiveawaysByIdGiveawayIdRoute =
  GSlugGiveawaysByIdGiveawayIdRouteImport.update({
    id: '/g/$slug/giveaways/by-id/$giveawayId',
    path: '/g/$slug/giveaways/by-id/$giveawayId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/admin/cookies': typeof AdminCookiesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/$appId': typeof AppAppIdRoute
  '/mod/audit': typeof ModAuditRoute
  '/sub/$subId': typeof SubSubIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/mod/': typeof ModIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/start': typeof AuthSteamStartRoute
  '/g/$slug/wins': typeof GSlugWinsRoute
  '/mod/g/$slug': typeof ModGSlugRoute
  '/mod/wins/$winId': typeof ModWinsWinIdRoute
  '/u/steam/$steamId': typeof USteamSteamIdRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/g/$slug/giveaways/$code': typeof GSlugGiveawaysCodeRoute
  '/g/$slug/giveaways/': typeof GSlugGiveawaysIndexRoute
  '/g/$slug/giveaways/by-id/$giveawayId': typeof GSlugGiveawaysByIdGiveawayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/admin/cookies': typeof AdminCookiesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/$appId': typeof AppAppIdRoute
  '/mod/audit': typeof ModAuditRoute
  '/sub/$subId': typeof SubSubIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/mod': typeof ModIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/start': typeof AuthSteamStartRoute
  '/g/$slug/wins': typeof GSlugWinsRoute
  '/mod/g/$slug': typeof ModGSlugRoute
  '/mod/wins/$winId': typeof ModWinsWinIdRoute
  '/u/steam/$steamId': typeof USteamSteamIdRoute
  '/g/$slug': typeof GSlugIndexRoute
  '/g/$slug/giveaways/$code': typeof GSlugGiveawaysCodeRoute
  '/g/$slug/giveaways': typeof GSlugGiveawaysIndexRoute
  '/g/$slug/giveaways/by-id/$giveawayId': typeof GSlugGiveawaysByIdGiveawayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/admin/cookies': typeof AdminCookiesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/$appId': typeof AppAppIdRoute
  '/mod/audit': typeof ModAuditRoute
  '/sub/$subId': typeof SubSubIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/mod/': typeof ModIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/start': typeof AuthSteamStartRoute
  '/g/$slug/wins': typeof GSlugWinsRoute
  '/mod/g/$slug': typeof ModGSlugRoute
  '/mod/wins/$winId': typeof ModWinsWinIdRoute
  '/u/steam/$steamId': typeof USteamSteamIdRoute
  '/g/$slug/': typeof GSlugIndexRoute
  '/g/$slug/giveaways/$code': typeof GSlugGiveawaysCodeRoute
  '/g/$slug/giveaways/': typeof GSlugGiveawaysIndexRoute
  '/g/$slug/giveaways/by-id/$giveawayId': typeof GSlugGiveawaysByIdGiveawayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/healthz'
    | '/login'
    | '/admin/cookies'
    | '/admin/groups'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/$appId'
    | '/mod/audit'
    | '/sub/$subId'
    | '/u/$username'
    | '/admin/'
    | '/mod/'
    | '/admin/users/$userId'
    | '/auth/steam/callback'
    | '/auth/steam/start'
    | '/g/$slug/wins'
    | '/mod/g/$slug'
    | '/mod/wins/$winId'
    | '/u/steam/$steamId'
    | '/g/$slug/'
    | '/g/$slug/giveaways/$code'
    | '/g/$slug/giveaways/'
    | '/g/$slug/giveaways/by-id/$giveawayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/healthz'
    | '/login'
    | '/admin/cookies'
    | '/admin/groups'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/$appId'
    | '/mod/audit'
    | '/sub/$subId'
    | '/u/$username'
    | '/admin'
    | '/mod'
    | '/admin/users/$userId'
    | '/auth/steam/callback'
    | '/auth/steam/start'
    | '/g/$slug/wins'
    | '/mod/g/$slug'
    | '/mod/wins/$winId'
    | '/u/steam/$steamId'
    | '/g/$slug'
    | '/g/$slug/giveaways/$code'
    | '/g/$slug/giveaways'
    | '/g/$slug/giveaways/by-id/$giveawayId'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/healthz'
    | '/login'
    | '/admin/cookies'
    | '/admin/groups'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/$appId'
    | '/mod/audit'
    | '/sub/$subId'
    | '/u/$username'
    | '/admin/'
    | '/mod/'
    | '/admin/users/$userId'
    | '/auth/steam/callback'
    | '/auth/steam/start'
    | '/g/$slug/wins'
    | '/mod/g/$slug'
    | '/mod/wins/$winId'
    | '/u/steam/$steamId'
    | '/g/$slug/'
    | '/g/$slug/giveaways/$code'
    | '/g/$slug/giveaways/'
    | '/g/$slug/giveaways/by-id/$giveawayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  AdminCookiesRoute: typeof AdminCookiesRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AppAppIdRoute: typeof AppAppIdRoute
  ModAuditRoute: typeof ModAuditRoute
  SubSubIdRoute: typeof SubSubIdRoute
  UUsernameRoute: typeof UUsernameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ModIndexRoute: typeof ModIndexRoute
  AuthSteamCallbackRoute: typeof AuthSteamCallbackRoute
  AuthSteamStartRoute: typeof AuthSteamStartRoute
  GSlugWinsRoute: typeof GSlugWinsRoute
  ModGSlugRoute: typeof ModGSlugRoute
  ModWinsWinIdRoute: typeof ModWinsWinIdRoute
  USteamSteamIdRoute: typeof USteamSteamIdRoute
  GSlugIndexRoute: typeof GSlugIndexRoute
  GSlugGiveawaysCodeRoute: typeof GSlugGiveawaysCodeRoute
  GSlugGiveawaysIndexRoute: typeof GSlugGiveawaysIndexRoute
  GSlugGiveawaysByIdGiveawayIdRoute: typeof GSlugGiveawaysByIdGiveawayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/': {
      id: '/mod/'
      path: '/mod'
      fullPath: '/mod/'
      preLoaderRoute: typeof ModIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub/$subId': {
      id: '/sub/$subId'
      path: '/sub/$subId'
      fullPath: '/sub/$subId'
      preLoaderRoute: typeof SubSubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/audit': {
      id: '/mod/audit'
      path: '/mod/audit'
      fullPath: '/mod/audit'
      preLoaderRoute: typeof ModAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cookies': {
      id: '/admin/cookies'
      path: '/admin/cookies'
      fullPath: '/admin/cookies'
      preLoaderRoute: typeof AdminCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/': {
      id: '/g/$slug/'
      path: '/g/$slug'
      fullPath: '/g/$slug/'
      preLoaderRoute: typeof GSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/steam/$steamId': {
      id: '/u/steam/$steamId'
      path: '/u/steam/$steamId'
      fullPath: '/u/steam/$steamId'
      preLoaderRoute: typeof USteamSteamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/wins/$winId': {
      id: '/mod/wins/$winId'
      path: '/mod/wins/$winId'
      fullPath: '/mod/wins/$winId'
      preLoaderRoute: typeof ModWinsWinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/g/$slug': {
      id: '/mod/g/$slug'
      path: '/mod/g/$slug'
      fullPath: '/mod/g/$slug'
      preLoaderRoute: typeof ModGSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/wins': {
      id: '/g/$slug/wins'
      path: '/g/$slug/wins'
      fullPath: '/g/$slug/wins'
      preLoaderRoute: typeof GSlugWinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/start': {
      id: '/auth/steam/start'
      path: '/auth/steam/start'
      fullPath: '/auth/steam/start'
      preLoaderRoute: typeof AuthSteamStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/callback': {
      id: '/auth/steam/callback'
      path: '/auth/steam/callback'
      fullPath: '/auth/steam/callback'
      preLoaderRoute: typeof AuthSteamCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/g/$slug/giveaways/': {
      id: '/g/$slug/giveaways/'
      path: '/g/$slug/giveaways'
      fullPath: '/g/$slug/giveaways/'
      preLoaderRoute: typeof GSlugGiveawaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/giveaways/$code': {
      id: '/g/$slug/giveaways/$code'
      path: '/g/$slug/giveaways/$code'
      fullPath: '/g/$slug/giveaways/$code'
      preLoaderRoute: typeof GSlugGiveawaysCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/giveaways/by-id/$giveawayId': {
      id: '/g/$slug/giveaways/by-id/$giveawayId'
      path: '/g/$slug/giveaways/by-id/$giveawayId'
      fullPath: '/g/$slug/giveaways/by-id/$giveawayId'
      preLoaderRoute: typeof GSlugGiveawaysByIdGiveawayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  AdminCookiesRoute: AdminCookiesRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AppAppIdRoute: AppAppIdRoute,
  ModAuditRoute: ModAuditRoute,
  SubSubIdRoute: SubSubIdRoute,
  UUsernameRoute: UUsernameRoute,
  AdminIndexRoute: AdminIndexRoute,
  ModIndexRoute: ModIndexRoute,
  AuthSteamCallbackRoute: AuthSteamCallbackRoute,
  AuthSteamStartRoute: AuthSteamStartRoute,
  GSlugWinsRoute: GSlugWinsRoute,
  ModGSlugRoute: ModGSlugRoute,
  ModWinsWinIdRoute: ModWinsWinIdRoute,
  USteamSteamIdRoute: USteamSteamIdRoute,
  GSlugIndexRoute: GSlugIndexRoute,
  GSlugGiveawaysCodeRoute: GSlugGiveawaysCodeRoute,
  GSlugGiveawaysIndexRoute: GSlugGiveawaysIndexRoute,
  GSlugGiveawaysByIdGiveawayIdRoute: GSlugGiveawaysByIdGiveawayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
